[package]
name = "clarity-repl"
version = "0.22.2"
description = "Clarity REPL"
authors = ["Ludo Galabru <ludo@hiro.so>", "Brice Dobry <brice@hiro.so>", "Reed Rosenbluth <reed@hiro.so>"]
readme = "README.md"
edition = "2018"
license = "GPL-3.0-only"
keywords = ["blockstack", "blockchain", "clarity", "smart-contract", "repl"]
exclude = [
    "vs-client/**",
    ".husky",
    ".git*"
    ]
homepage = "https://hirosystems.github.io/clarity-repl/"
repository = "https://github.com/hirosystems/clarity-repl"
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils"]

[dependencies]
ansi_term = "0.12.1"
lazy_static = "1.4.0"
regex = "1.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.47", features = ["unbounded_depth"] }
sha2 = "0.9.3"
sha3 = "0.9.1"
serde_derive = "1.0"
ripemd160 = "0.9.1"
integer-sqrt = "0.1.3"
libsecp256k1 = "0.5.0"
serde_stacker = "0.1"
rand = "=0.7.3"
getrandom = { version = "0.2.3", features = ["js"] }
rand_pcg = "0.3.1"
rand_seeder = "0.2.2"
atty = "0.2.14"
tokio = { version = "=1.15.0", features = ["rt", "rt-multi-thread"], optional = true }

# CLI
pico-args = { version = "0.4.0", optional = true }
rustyline = { version = "9.1.1", optional = true }
prettytable-rs = { version = "0.8.0", optional = true }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"], optional = true }

# WASM
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4.24", optional = true }
reqwest-wasm = { version = "0.11", features = ["json"], optional = true }

[lib]
name = "clarity_repl"
path = "src/lib.rs"
# Default type
# crate-type = ["lib"]

# Use this instead for WASM builds
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "clarity-repl"
path = "src/bin.rs"

[features]
default = ["cli"]
cli = ["pico-args", "rustyline", "prettytable-rs", "reqwest", "tokio"]
wasm = ["wasm-bindgen", "reqwest-wasm", "wasm-bindgen-futures"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false
